language: go

go:
  - "1.13"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libasound2-dev
      - libgl1-mesa-dev
      - libalut-dev
      - libxcursor-dev
      - libxi-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxxf86vm-dev
  chrome: stable

services:
  - xvfb

install:
  - go get golang.org/dl/go1.12.9
  - go1.12.9 download
  - mkdir /tmp/work
  - cd /tmp/work
  - go mod init example.com/m
  - go get github.com/hajimehoshi/ebiten@$TRAVIS_BRANCH
  - # gopath-get for the current GopherJS and gjbt.
  - GO111MODULE=off go get -tags example github.com/hajimehoshi/ebiten/... 
  - GO111MODULE=off go1.12.9 get github.com/gopherjs/gopherjs
  - GO111MODULE=off go1.12.9 get myitcv.io/cmd/gjbt
  - mkdir /tmp/google-chrome-bin
  - ln -s /usr/bin/google-chrome-stable /tmp/google-chrome-bin/google-chrome
  - export PATH=/tmp/google-chrome-bin:$PATH
  - curl -s https://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip > /tmp/chromedriver_linux64.zip
  - unzip -d /tmp/chromedriver_linux64 /tmp/chromedriver_linux64.zip
  - export PATH=/tmp/chromedriver_linux64:$PATH

before_script:
  - export DISPLAY=:99.0

script:
  - cd /tmp/work
  - go build -tags example -v github.com/hajimehoshi/ebiten/...
  - go test -v github.com/hajimehoshi/ebiten/...
  - GOOS=windows GOARCH=amd64 go build -tags example -v github.com/hajimehoshi/ebiten/...
  - GOOS=windows GOARCH=386 go build -tags example -v github.com/hajimehoshi/ebiten/...
  - GO111MODULE=off go1.12.9 run github.com/gopherjs/gopherjs build --tags example -v github.com/hajimehoshi/ebiten/examples/blocks
  - GO111MODULE=off go1.12.9 run myitcv.io/cmd/gjbt github.com/hajimehoshi/ebiten # TODO: Test the subdirectories

# - test -z $(gofmt -s -l $GOPATH/src/github.com/hajimehoshi/ebiten)

notifications:
  email:
    recipients:
      - hajimehoshi@gmail.com
