language: go

go:
  - 1.5

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libglew-dev # required by node-gl.
      - libglfw3-dev
      - libopenal-dev
      - libalut-dev
      - libxxf86vm-dev

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export NODE_PATH=$(npm config get prefix)/lib/node_modules
  - npm install --global gl

install:
  - go get -t -v ./...
  - go get github.com/gopherjs/gopherjs
  - go get github.com/gopherjs/webgl

script:
  - go test -v ./...
  - gopherjs test -v github.com/hajimehoshi/ebiten github.com/hajimehoshi/ebiten/internal/graphics
  - gopherjs build -v github.com/hajimehoshi/ebiten/example/blocks

notifications:
  email:
    recipients:
      - hajimehoshi@gmail.com
