name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest]
        go: ['1.19.x']
    name: Test with Go ${{ matrix.go }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      DISPLAY: ':99.0'
    defaults:
      run:
        shell: bash
    steps:
      - name: Git
        run: |
          # See actions/checkout#135
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          cache: true

      - name: Install wasmbrowsertest
        run: |
          go install github.com/agnivade/wasmbrowsertest@8753b3a64e2d666fd88734888f26e48c68882f5f
          mv $(go env GOPATH)/bin/wasmbrowsertest${{ runner.os == 'Windows' && '.exe' || '' }} $(go env GOPATH)/bin/go_js_wasm_exec${{ runner.os == 'Windows' && '.exe' || '' }}

      - name: go test (Wasm)
        run: |
          cp .github/workflows/wasm_exec.js $(go env GOROOT)/misc/wasm/wasm_exec.js
          GO_FULLPATH=$(which go)
          env GOOS=js GOARCH=wasm PATH= $GO_FULLPATH test -shuffle=on -v ./...
          env GOOS=js GOARCH=wasm EBITENGINE_OPENGL=webgl1 PATH= $GO_FULLPATH test -shuffle=on -v ./...
